### ISSUE TITLE
Support for LCD display and buttons?

### ISSUE THREAD

**Issue by linkedupbits** [Makin-Things/ESPHome-Brivis-Networker#1]
Could this be extended to support a display and physical buttons?

If I understand correctly, this needs to replace the BR2 completely, so making this unit autonomous from Home Assistant (if HA is down) would be great.

Could the existing pin outs be used for this - IC2 for a display and buttons?

**Comment by Makin-Things** [comment]
Depending on the version of NC you have you can in theory have it coexist the the existing controller. I think you need an NC-3 or later as that is where they added the ability to set a device id.
I won't be adding a screen or buttons as it is not something I need.
